language: node_js
node_js:
  - 10
before_install:
  - npm i -g npm@6.4.1
install:
  - npm install -g codecov
cache: npm
script:
  - npm run build
  - npm run test:ci && cat ./coverage/lcov.info | coveralls && codecov

