language: node_js
node_js:
  - 10
install:
  - npm install -g codecov
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm run test:ci && cat ./coverage/lcov.info | coveralls && codecov

